openapi: 3.0.0
info:
  title: 'TiSaude API'
  version: '0.1'
paths:
  /api/appointments:
    get:
      tags:
        - Consultas
      summary: 'Lista de Consultas'
      description: 'Lista de Consultas'
      operationId: 812c4f15927f3d0e3e959538a6f1104b
      responses:
        '200':
          description: 'Lista de Consultas'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - Consultas
      summary: 'Cria um nova Consulta'
      description: 'Cria um nova Consulta'
      operationId: 2b481df28ec53d2afb2ec7c9a3a77846
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Cria um nova Consulta'
      security:
        -
          bearerAuth: []
  '/api/appointments/{id}':
    get:
      tags:
        - Consultas
      summary: 'Exibe uma Consulta'
      description: 'Exibe uma Consulta'
      operationId: cca217dc71eae262de1fe09f314a4948
      parameters:
        -
          name: id
          in: path
          description: 'ID da Consulta'
          required: true
      responses:
        '200':
          description: 'Exibe uma Consulta'
      security:
        -
          bearerAuth: []
    put:
      tags:
        - Consultas
      summary: 'Atualiza uma Consulta'
      description: 'Atualiza uma Consulta'
      operationId: 56cd9e193d590ed31b28bf8fe7162e70
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Atualiza uma Consulta'
      security:
        -
          bearerAuth: []
    delete:
      tags:
        - Consultas
      summary: 'Deleta uma Consulta'
      description: 'Deleta uma Consulta'
      operationId: 47535f80ea6b8f4309694ff2123524d3
      responses:
        '200':
          description: 'Deleta uma Consulta'
      security:
        -
          bearerAuth: []
  '/api/appointments/{id}/add-procedures':
    post:
      tags:
        - Consultas
      summary: 'Adiciona um ou vários procedimentos a uma Consulta'
      description: 'Adiciona um ou vários procedimentos a uma Consulta'
      operationId: 3cbe92b2cdcc26801f4dd51912806250
      parameters:
        -
          name: id
          in: path
          description: 'ID da Consulta'
          required: true
        -
          name: 'procedures_ids[]'
          in: query
          description: 'IDs dos Procedimentos'
          required: true
          schema:
            type: array
            items:
              type: integer
            minItems: 1
      responses:
        '200':
          description: 'Procedimentos adicionadas'
  '/api/doctors/{id}/remove-procedure':
    post:
      tags:
        - Consultas
      summary: 'Remove um procedimento de uma Consulta'
      description: 'Remove um procedimento de uma Consulta'
      operationId: 3fc0decd72a3c83da04272ac38b40530
      parameters:
        -
          name: id
          in: path
          description: 'ID da Consulta'
          required: true
        -
          name: procedure_id
          in: query
          description: 'ID do Procedimento'
          required: true
      responses:
        '200':
          description: 'Procedimento removido'
  /api/auth/login:
    post:
      tags:
        - Autenticação
      summary: 'Realiza o login na API'
      description: 'Retorna informaçõs do usuário e o TOKEN de acesso'
      operationId: dd51a484b7fa0f97c7680fdbde14cf5f
      parameters:
        -
          name: email
          in: query
          description: 'E-mail de credencial de acesso (user@tisaude.com.br)'
          required: true
        -
          name: password
          in: query
          description: 'Senha de credencial de acesso (tisaude123@)'
          required: true
      responses:
        '200':
          description: 'Retorna informaçõs do usuário e o TOKEN de acesso'
      security:
        -
          bearerAuth: []
  /api/auth/logout:
    post:
      tags:
        - Autenticação
      summary: 'Realiza o logout na API'
      description: 'Invalida o token de acesso do usuário'
      operationId: df9bdc6c7a6d9f20b983526b2ec0f698
      responses:
        '200':
          description: 'Invalida o token de acesso do usuário'
  /api/doctors:
    get:
      tags:
        - Médicos
      summary: 'Lista de Médicos'
      description: 'Lista de Médicos'
      operationId: 4479c235c75c92e2425c15211470f478
      responses:
        '200':
          description: 'Lista de Médicos'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - Médicos
      summary: 'Cria um novo Médico'
      description: 'Cria um novo Médico'
      operationId: ee9dd1ffdbcab8d6d47b2dd0bd06ed9b
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Cria um novo Médico'
      security:
        -
          bearerAuth: []
  '/api/doctors/{id}':
    get:
      tags:
        - Médicos
      summary: 'Exibe um Médico'
      description: 'Exibe um Médico'
      operationId: d38f21421c3eca3294015240d2d7e1ad
      parameters:
        -
          name: id
          in: path
          description: 'ID do Médico'
          required: true
      responses:
        '200':
          description: 'Exibe um Médico'
      security:
        -
          bearerAuth: []
    put:
      tags:
        - Médicos
      summary: 'Atualiza um Médico'
      description: 'Atualiza um Médico'
      operationId: dd6e159937989a95449bd7ebab306776
      parameters:
        -
          name: id
          in: path
          description: 'ID do Médico'
          required: true
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Atualiza um Médico'
      security:
        -
          bearerAuth: []
    delete:
      tags:
        - Médicos
      summary: 'Deleta um Médico'
      description: 'Deleta um Médico'
      operationId: 04bc41e2ab78cd139c19896955c012af
      parameters:
        -
          name: id
          in: path
          description: 'ID do Médico'
          required: true
      responses:
        '200':
          description: 'Deleta um Médico'
      security:
        -
          bearerAuth: []
  '/api/doctors/{id}/add-specialties':
    post:
      tags:
        - Médicos
      summary: 'Adiciona uma ou várias especialidades a um Médico'
      description: 'Adiciona uma ou várias especialidades a um Médico'
      operationId: c6d845b351eadd89376732277c8c73bd
      parameters:
        -
          name: id
          in: path
          description: 'ID do Médico'
          required: true
        -
          name: 'specialty_ids[]'
          in: query
          description: 'IDs das Especialidades'
          required: true
          schema:
            type: array
            items:
              type: integer
            minItems: 1
      responses:
        '200':
          description: 'Especialidades adicionadas'
      security:
        -
          bearerAuth: []
  '/api/doctors/{id}/remove-specialties':
    post:
      tags:
        - Médicos
      summary: 'Remove uma especialidade de um Médico'
      description: 'Remove uma especialidade de um Médico'
      operationId: 545fee247760e172a6fc982d60a25995
      parameters:
        -
          name: id
          in: path
          description: 'ID do Médico'
          required: true
        -
          name: specialty_id
          in: query
          description: 'ID da Especialidade'
          required: true
      responses:
        '200':
          description: 'Especialidade removida'
      security:
        -
          bearerAuth: []
  '/api/doctors/{id}/appointments':
    get:
      tags:
        - Médicos
      summary: 'Exibe as consultas de um Médico'
      description: 'Exibe as consultas de um Médico'
      operationId: 5ee5f439de5bb850a0848a40886ae446
      parameters:
        -
          name: id
          in: path
          description: 'ID do Médico'
          required: true
      responses:
        '200':
          description: 'Consulta do Médico'
      security:
        -
          bearerAuth: []
  /api/health-plans:
    get:
      tags:
        - 'Planos de Saúde'
      summary: 'Lista de Planos de Saúde'
      description: 'Lista de Planos de Saúde'
      operationId: c42399d781b6dc6f9f5dda34c5ee6067
      responses:
        '200':
          description: 'Lista de Planos de Saúde'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - 'Planos de Saúde'
      summary: 'Cria um novo Plano de Saúde'
      description: 'Cria um novo Plano de Saúde'
      operationId: 256b9f08a9bac77e63fde8fd5308ff3e
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Cria um novo Plano de Saúde'
      security:
        -
          bearerAuth: []
  '/api/health-plans/{id}':
    get:
      tags:
        - 'Planos de Saúde'
      summary: 'Exibe um Plano de Saúde'
      description: 'Exibe um Plano de Saúde'
      operationId: 7f01b4dd94277aed2d32692c26851714
      parameters:
        -
          name: id
          in: path
          description: 'ID do Plano de Saúde'
          required: true
      responses:
        '200':
          description: 'Exibe um Plano de Saúde'
      security:
        -
          bearerAuth: []
    put:
      tags:
        - 'Planos de Saúde'
      summary: 'Atualiza um Plano de Saúde'
      description: 'Atualiza um Plano de Saúde'
      operationId: 85ee0cab27cff3c6c98a5b729d63d27e
      parameters:
        -
          name: id
          in: path
          description: 'ID do Plano de Saúde'
          required: true
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Atualiza um Plano de Saúde'
      security:
        -
          bearerAuth: []
    delete:
      tags:
        - 'Planos de Saúde'
      summary: 'Deleta um Plano de Saúde'
      description: 'Deleta um Plano de Saúde'
      operationId: 380b50e73f926dc40f1aa04faf45e4dd
      parameters:
        -
          name: id
          in: path
          description: 'ID do Plano de Saúde'
          required: true
      responses:
        '200':
          description: 'Deleta um Plano de Saúde'
      security:
        -
          bearerAuth: []
  /api/pacients:
    get:
      tags:
        - Pacientes
      summary: 'Lista de Pacientes'
      description: 'Lista de Pacientes'
      operationId: 3549af4e35db6d775f55ecf368fec281
      responses:
        '200':
          description: 'Lista de Pacientes'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - Pacientes
      summary: 'Cria um novo Paciente'
      description: 'Cria um novo Paciente'
      operationId: 56efce158a5c319d998932b7a6ceec84
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Cria um novo Paciente'
      security:
        -
          bearerAuth: []
  '/api/pacients/{id}':
    get:
      tags:
        - Pacientes
      summary: 'Exibe um Paciente'
      description: 'Exibe um Paciente'
      operationId: 2ea05843b7246dcc33e2df47ae72f2e2
      parameters:
        -
          name: id
          in: path
          description: 'ID do Paciente'
          required: true
      responses:
        '200':
          description: 'Exibe um Paciente'
      security:
        -
          bearerAuth: []
    put:
      tags:
        - Pacientes
      summary: 'Atualiza um Paciente'
      description: 'Atualiza um Paciente'
      operationId: 6631e4ca15795ee7c1bea2ffbf998558
      parameters:
        -
          name: id
          in: path
          description: 'ID do Paciente'
          required: true
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Atualiza um Paciente'
      security:
        -
          bearerAuth: []
    delete:
      tags:
        - Pacientes
      summary: 'Deleta um Paciente'
      description: 'Deleta um Paciente'
      operationId: 8ce10996f68a2007ba5cf78c2b96cd0d
      parameters:
        -
          name: id
          in: path
          description: 'ID do Paciente'
          required: true
      responses:
        '200':
          description: 'Deleta um Paciente'
      security:
        -
          bearerAuth: []
  /api/pacients-health-plan:
    get:
      tags:
        - 'Planos de Saúde dos Pacientes'
      summary: 'Lista os Planos de Saúde dos Pacientes'
      description: 'Lista Planos de Saúde dos Pacientes'
      operationId: 6d3158c38d0b449e71a8e14f507f03dd
      responses:
        '200':
          description: 'Lista Planos de Saúde dos Pacientes'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - 'Planos de Saúde dos Pacientes'
      summary: 'Cria um Planos de Saúde para o Paciente'
      description: 'Cria um Planos de Saúde para o Paciente'
      operationId: f2e2cc9e493aa940aeecaf7cda647e35
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Criado com sucesso'
      security:
        -
          bearerAuth: []
  '/api/pacients-health-plan/{id}':
    get:
      tags:
        - 'Planos de Saúde dos Pacientes'
      summary: 'Lista o Plano de Saúde do Paciente'
      description: 'Lista o Plano de Saúde do Paciente'
      operationId: 81885fd6efa338c33ffcbd577541ba22
      parameters:
        -
          name: id
          in: path
          description: ID
          required: true
      responses:
        '200':
          description: 'Plano exibido'
      security:
        -
          bearerAuth: []
    put:
      tags:
        - 'Planos de Saúde dos Pacientes'
      summary: 'Atualiza o Plano de Saúde do Paciente'
      description: 'Atualiza o Plano de Saúde do Paciente'
      operationId: e37c7b064e40e969da6ef31652e04fec
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
        -
          name: id
          in: path
          description: ID
          required: true
      responses:
        '200':
          description: 'Plano atualizado'
      security:
        -
          bearerAuth: []
    delete:
      tags:
        - 'Planos de Saúde dos Pacientes'
      summary: 'Deleta o Plano de Saúde do Paciente'
      description: 'Deleta o Plano de Saúde do Paciente'
      operationId: b17b79d5692f7cc84c47ba822b8ef0f5
      parameters:
        -
          name: id
          in: path
          description: ID
          required: true
      responses:
        '200':
          description: 'Plano deletado'
      security:
        -
          bearerAuth: []
  /api/procedures:
    get:
      tags:
        - Procedimentos
      summary: 'Lista de Procedimentos'
      description: 'Lista de Procedimentos'
      operationId: 7d6ba815589b5f6a122b0c3362e8b177
      responses:
        '200':
          description: 'Lista de Procedimentos'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - Procedimentos
      summary: 'Cria um novo Procedimento'
      description: 'Cria um novo Procedimento'
      operationId: 65ae2b00841b4a1ab0896811636e8065
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Cria um novo Procedimento'
      security:
        -
          bearerAuth: []
  '/api/procedures/{id}':
    get:
      tags:
        - Procedimentos
      summary: 'Exibe um procedimento'
      description: 'Exibe um procedimento'
      operationId: 7d7cd20f72364dc472c949ad5465383b
      parameters:
        -
          name: id
          in: path
          description: 'ID do Procedimento'
          required: true
      responses:
        '200':
          description: 'Exibe um procedimento'
      security:
        -
          bearerAuth: []
    put:
      tags:
        - Procedimentos
      summary: 'Atualiza um procedimento'
      description: 'Atualiza um procedimento'
      operationId: b02480753e102fe3bca0473abf88b626
      parameters:
        -
          name: id
          in: path
          description: 'ID do Procedimento'
          required: true
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Atualiza um procedimento'
      security:
        -
          bearerAuth: []
    delete:
      tags:
        - Procedimentos
      summary: 'Deleta um procedimento'
      description: 'Deleta um procedimento'
      operationId: a9c66777a1bdff4ce6549c220a927bfa
      parameters:
        -
          name: id
          in: path
          description: 'ID do Procedimento'
          required: true
      responses:
        '200':
          description: 'Deleta um procedimento'
      security:
        -
          bearerAuth: []
  /api/specialties:
    get:
      tags:
        - Especialidades
      summary: 'Lista as especialidades'
      description: 'Lista as especialidades'
      operationId: 67515fb7ae55ba00df38f3069860eba8
      responses:
        '200':
          description: 'Lista as especialidades'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - Especialidades
      summary: 'Cria uma nova especialidades'
      description: 'Cria uma nova especialidades'
      operationId: 6ffffb6d94d102c82f2081765ba7bdae
      parameters:
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Cria uma nova especialidades'
      security:
        -
          bearerAuth: []
  '/api/specialties/{id}':
    get:
      tags:
        - Especialidades
      summary: 'Lista uma especialidade'
      description: 'Lista uma especialidade'
      operationId: b2731d1377c994d3814193cd2edcc834
      parameters:
        -
          name: id
          in: path
          description: 'ID da Especialidade'
          required: true
      responses:
        '200':
          description: 'Lista uma especialidade'
      security:
        -
          bearerAuth: []
    put:
      tags:
        - Especialidades
      summary: 'Atualiza uma especialidades'
      description: 'Atualiza uma especialidades'
      operationId: 00783a2640e0f8ddb81ccfeb1cecd2e2
      parameters:
        -
          name: id
          in: path
          description: 'ID da Especialidade'
          required: true
        -
          name: name
          in: query
          description: Nome
          required: true
      responses:
        '200':
          description: 'Atualiza uma especialidades'
      security:
        -
          bearerAuth: []
    delete:
      tags:
        - Especialidades
      summary: 'Deleta uma especialidades'
      description: 'Deleta uma especialidades'
      operationId: 129546f791893572810b5f9006c6de58
      parameters:
        -
          name: id
          in: path
          description: 'ID da Especialidade'
          required: true
      responses:
        '200':
          description: 'Deleta uma especialidades'
      security:
        -
          bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
